apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetic-retinopathy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: diabetic-retinopathy-app:latest
          imagePullPolicy: Never  # Important: Use local image
          ports:
            - containerPort: 5000
